name: Run Puppeteer Script

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  puppeteer-job:
    runs-on: ubuntu-22.04

    steps:
      # Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

        # Install xvfb and dependencies
      - name: Install Xvfb and Puppeteer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libgbm1 libpango-1.0-0 libasound2 fonts-liberation libappindicator3-1 xdg-utils

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run Puppeteer script
      - name: Run Puppeteer Script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
        run: |
          xvfb-run --auto-servernum -- node main.js
