name: Run Puppeteer Script

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  puppeteer-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install required dependencies
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      - name: Run Puppeteer Script
        uses: run-with-xvfb
        with:
          run: node main.js
        env:
          CI: true
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}

      # - name: Run Puppeteer Script
      #   env:
      #     TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      #     TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      #     TWILIO_TO: ${{ secrets.TWILIO_TO }}
      #     TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
      #   run: node main.js
